# Generated by Django 3.1.4 on 2020-12-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='detail')),
                ('is_important', models.BooleanField(default=False, verbose_name='is_important')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is_completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed_at')),
            ],
            options={
                'verbose_name': 'todo',
                'verbose_name_plural': 'todos',
                'ordering': ['id'],
            },
        ),
    ]
